# Generated by Django 5.2.3 on 2025-07-14 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_addr', models.CharField(db_index=True, max_length=13, verbose_name='Destination')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(db_index=True, default='Sent', max_length=16)),
                ('sent_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient_type', models.CharField(choices=[('guardian', 'Guardian'), ('staff', 'Staff'), ('other', 'Other')], default='guardian', max_length=10)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('source_addr', models.CharField(default='ST.TH-AVILA', max_length=50)),
                ('length', models.PositiveIntegerField(default=0)),
                ('sms_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-sent_date'],
                'indexes': [models.Index(fields=['dest_addr'], name='sms_sentsms_dest_ad_1c8782_idx'), models.Index(fields=['sent_date'], name='sms_sentsms_sent_da_ca4619_idx')],
            },
        ),
    ]
