# Generated by Django 5.2.3 on 2025-07-01 02:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+255\\d{9}$', 'Use +255XXXXXXXXX format (Tanzanian mobile).')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='school.academicyear')),
            ],
            options={
                'ordering': ['academic_year__year', 'name'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('guardian1_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+255\\d{9}$', 'Use +255XXXXXXXXX format (Tanzanian mobile).')])),
                ('guardian2_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+255\\d{9}$', 'Use +255XXXXXXXXX format (Tanzanian mobile).')])),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.schoolclass')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('guardian1_phone__regex', '^\\+255\\d{9}$')), name='guardian1_format_ok'), models.CheckConstraint(condition=models.Q(('guardian2_phone__isnull', True), ('guardian2_phone__regex', '^\\+255\\d{9}$'), _connector='OR'), name='guardian2_format_ok')],
            },
        ),
    ]
