# Generated by Django 5.2.3 on 2025-07-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_current_class_studentclassassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='school.academicyear'),
        ),
        migrations.AlterField(
            model_name='studentclassassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='school.schoolclass'),
        ),
    ]
