"""
Django settings for myschool project.
Generated by 'django-admin startproject' using Django 5.2.3
"""

from pathlib import Path

# ─────────────── Core paths ──────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ─────────────── Security ────────────────────────────────────────────────
SECRET_KEY = 'django-insecure-#sr3r^m2yjdq$c$3h7lv-&4bpkeuw4%x=@tb6atgdl_n4ix3sx'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app']

# ─────────────── Custom user / authentication ───────────────────────────
AUTH_USER_MODEL = 'accounts.CustomUser'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.UsernameOrPhoneBackend',          # phone or username
    'django.contrib.auth.backends.ModelBackend',        # default
]

LOGIN_REDIRECT_URL = 'home'     # ⭢  index page after sign‑in
LOGOUT_REDIRECT_URL = 'home'    # ⭢  index page after logout
LOGIN_URL = 'login'             # where @login_required sends guests

# ─────────────── Installed apps ─────────────────────────────────────────
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third‑party
    'widget_tweaks',

    # Local
    'school',
    'accounts',
    'sms',
]

# ─────────────── Middleware ──────────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ─────────────── URLs / WSGI ─────────────────────────────────────────────
ROOT_URLCONF = 'myschool.urls'
WSGI_APPLICATION = 'myschool.wsgi.application'

# ─────────────── Templates ───────────────────────────────────────────────
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project‑level templates folder plus app templates discovered via APP_DIRS
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'school/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ─────────────── Database ────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ─────────────── Password validation ─────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ─────────────── Internationalisation ────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Dar_es_Salaam'
USE_I18N = True
USE_TZ = True

# ─────────────── Static & media files ────────────────────────────────────
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─────────────── Messages framework ──────────────────────────────────────
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ─────────────── CSRF (ngrok) ────────────────────────────────────────────
CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']

# ─────────────── Logging ─────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        '': {                   # root logger
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'school': {             # app‑specific
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {             # Django internals
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# ─────────────── Default primary key type ────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
